### ISSUE TITLE
XRB poached from wallet

### ISSUE THREAD

**Issue by chucknorris1313** [clemahieu/raiblocks#166]
Somehow account xrb_1ywh6f4fujk6tsnxiwr4b9d3p7yi43sm4kr56xhsrsk6aqgjphdxyeu93qar was able to poach 10,200 XRB from my wallet. You can find transactions here: xrb_1qn1htdu9wzbyqrmxg4836kjedmmq455nm5sgqmw48ksqx4577aqd6yo14t4

V7.9.0 wallet

**Comment by clemahieu** [comment]
How is this possible without them knowing your private key?

**Comment by chucknorris1313** [comment]
Created that wallet / account yesterday and only wrote down the wallet seed. The wallet was unlocked at the time of the transactions, if that plays a role. It looks like that XRB ended up in an account with over 3M XRB in it... xrb_3decyj8e1kpzrthikh79x6dwhn8ei81grennibmt43mcm9o8fgxqd8t46whj

This personal hiccup aside, appreciate your time/effort with this interesting project.

**Comment by clemahieu** [comment]
There are two possibilities:
1) Some knows a fatal flaw in the protocol but decided to take your 10,000 xrb instead of a much larger wallet like one with several million in it.
2) Your local computer was compromised and someone was able to access your private key.

Let me know if you have found a critical flaw in the code otherwise it seems like someone had access to your computer and stole it.
