### ISSUE TITLE
Build in centos 7.3 with Error..

### ISSUE THREAD

**Issue by aroncds** [clemahieu/raiblocks#245]
Hello people! I'm trying to build, but this one with error:

$ make rai_node
[  0%] Building CXX object CMakeFiles/node.dir/rai/node/node.cpp.o
c++: internal compiler error: Died (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
make[3]: ** [CMakeFiles/node.dir/rai/node/node.cpp.o] Erro 4
make[2]: ** [CMakeFiles/node.dir/all] Erro 2
make[1]: ** [CMakeFiles/rai_node.dir/rule] Erro 2
make: ** [rai_node] Erro 2

Centos: 7.3
GCC: 4.8.5, with 5.3.0 happens the same error
Boost: 1.6.3

Trying run the rai_node builded, but is requiring the GLIBC 2.18 and the centos 7 is 2.17

**Comment by androm3da** [comment]
This is an internal compiler error, so the bug is with gcc.  Please open a bug with the gcc team.

I would expect that gcc can tell you the nature of the problem and which gcc release fixes it.  CentOS team might be able to take a fix for this error.  Also, the original gcc bug will probably explain the nature of the problem so that we could look into a workaround that we could consider to avoid the problem.

**Comment by clemahieu** [comment]
Just as a sanity check, the machine isn't running out of memory is it?

**Comment by aroncds** [comment]
Is possible that is memory, the machine has 1.6gb, when the file node.cpp is being compiled, on moment that fills fully the memory.. happen the error...

**Comment by SergiySW** [comment]
You can try to increase swap

**Comment by aroncds** [comment]
Ooh thanks! I had not thought of that! Was on the tutorial of the ubuntu... Sorry guys!
