### ISSUE TITLE
No Incentive for maintaining Blockchain Integrity - Should add fallback incentive system

### ISSUE THREAD

**Issue by ghost** [clemahieu/raiblocks#501]
Restated Issue:  I would like to say that this is an issue for possible security decades out (in case the coin loses popularity) -
I would recommend adding an emergency incentive system if nodes on the network become very low to the point that the possibility of 100% node outage is imminent.
----original---
Am I completely out of my mind or is there absolutely no incentive for anyone to activate any DPOS feature and absolutely have the unrestrained possibility of an insecure network?

Why would anyone participate in an authentic manner securing the network if there is 0 incentive via new coin generation or via fees? Is there any new implementation of code that prevents a total network collapse of creation of new blocks besides trust in an enthusiast to run a DPOS node for no financial benefit??

**Comment by PlasmaPower** [comment]
There were about 1.4k nodes last I checked. I don't think this is a problem. Plus, some people do have to run nodes, such as exchanges.

**Comment by deusXmaximus** [comment]
Why do any people run a node for it without incentive? Isn't this exactly why PoW was created vs using nothing though?

**Comment by PlasmaPower** [comment]
Exchanges need to run nodes to find consensus. Users who store large amounts of XRB may also run nodes for enhanced security compared to light wallets.

We'll worry about this problem if it actually becomes a problem.

**Comment by deusXmaximus** [comment]
Okay - Can I rephrase this issue so that it may stay open in order to receive a PR one day -- I would like to say that this is an issue for possible security decades out (in case the coin loses popularity) - 
I would recommend adding an emergency incentive system if nodes on the network become very low to the point that the possibility of 100% node outage is imminent. Sound reasonable?

**Comment by PlasmaPower** [comment]
Sounds like a pain to implement for an (IMO) unlikely scenario.

**Comment by deusXmaximus** [comment]
Just so maybe someone will contribute a free PR for this addition that can be added if the trend looks toward this direction perhaps.

**Comment by sharabash** [comment]
+1

**Comment by androm3da** [comment]
If you hold XRB you are incentivized to run a node.

> Why would anyone participate in an authentic manner securing the network if there is 0 incentive via new coin generation or via fees? 

You would do it in order to preserve the value of your stake.  Your stake is your incentive.  If you can't host a node to preserve your stake's value then you risk its value being eliminated.

The lack of transaction fees and fixed inflation are features, by design, of the coin.

I'll close this issue, reopen it if you think it still needs to be addressed.  But don't open it in the hopes of getting a pull request to magically fix it -- the presence or absence of this issue isn't going to make the difference in getting a PR.  That PR would have an uphill battle just getting merged.

**Comment by AmirWaleed** [comment]
Given the issues you guys have I would suggest you guys stop turning down issues that are actually issues. The free "PR" would be free for you, not him. Instead of holding XRB people will dump it if it is not a safe store of even itself....

**Comment by androm3da** [comment]
This element is fundamental to the coin's design.  You are free to create your own coin with a different design.

The coin is safe.
